### ISSUE TITLE
Draft Deliverable

### ISSUE THREAD

**Issue by calebki94** [AmherstCollege/STAT370-S16-GroupIV#1]

**Comment by nicholasjhorton** [comment]
YOU WROTE: Hi Nick 

We apologize for submitting our draft a little late.

We've put everything on github and we are attaching the pdfs.

We will be adding the visuals for 13.3 but we were just wondering if we just need to do a mosaic plot like we did for 13.25.

Caleb has a frisbee tournament all day tomorrow and Melody will be working at the Admissions office all day tomorrow because of Admitted students event. Caleb will be leaving at 6am and not returning till around dinnertime. Is there any way we would be able to submit our final draft past 6pm?

Many thanks
Group IV


MY RESPONSE: You may submit your final versions by midnight tonight without penalty.  Please be sure to close the issue that you opened when you do this.
